author:
  - name: Daisuke Miyazaki
  - email: daisuke.miyazaki012@gmail.com
permalink: pretty
url: "https://mdaisuke.net"
baseurl: ""
sass_dir: _sass
sass:
  style: nested

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-sitemap

postcss:
  cache: false
title: Daisuke Miyazaki's Blog

markdown: kramdown
exclude: ["node_modules"]

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
